<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'command' => '/src/functions.php',
                'createevent' => '/src/functions.php',
                'eventcommand' => '/src/functions.php',
                'loginuser' => '/src/functions.php',
                'organisatorcommand' => '/src/functions.php',
                'registeruser' => '/src/functions.php',
                'search' => '/src/functions.php',
                'usercommand' => '/src/functions.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
